image: gitpod/workspace-full

tasks:
  - name: Install dependencies
    init: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser
      pip install selenium webdriver-manager

ports:
  - port: 3000
    onOpen: open-preview
